services:
    memorias-de-vida:
        container_name: memorias-de-vida
        build: .
        restart: always
        ports:
            - 127.0.0.1:4321:4321
        env_file:
            - .env
        environment:
            - HOST=0.0.0.0
